# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fridayUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FRIDAY_AI_ASSISTANT(object):
    def setupUi(self, FRIDAY_AI_ASSISTANT):
        FRIDAY_AI_ASSISTANT.setObjectName("FRIDAY_AI_ASSISTANT")
        FRIDAY_AI_ASSISTANT.resize(1253, 836)
        self.centralwidget = QtWidgets.QWidget(FRIDAY_AI_ASSISTANT)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, -5, 1251, 841))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("friday-ai-assistant\images\4NB4.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(370, 520, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(73, 111, 171);\n"
"border-radius:25px;")
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 520, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(201, 12, 28);\n"
"border-radius:25px")
        self.pushButton_2.setObjectName("pushButton_2")

        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(790, 50, 271, 81))
        self.textBrowser_4.setStyleSheet("font: 75 18pt \"Palatino Linotype\";\n"
"background:transparent;\n"
"border-radius:none;\n" "color:white;")

        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(960, 50, 271, 81))
        self.textBrowser_5.setStyleSheet("font: 75 18pt \"Palatino Linotype\";\n"
"background:transparent;\n"
"border-radius:none;\n" "color:white;")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 670, 1241, 131))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("friday-ai-assistant\images\W9dC.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(750, 130, 551, 381))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("friday-ai-assistant\images\7AMX.gif"))
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 180, 361, 321))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("friday-ai-assistant\images\output-onlinegiftools.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, -20, 681, 211))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("friday-ai-assistant\images\Jarvis_Loading_Screen.mp4"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(380, 210, 361, 291))
        self.textBrowser.setStyleSheet("background:transparent;\n"
"font-size:14px;\n"
"border-radius:none;")
        self.textBrowser.setObjectName("textBrowser")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(580, 140, 201, 71))
        self.label_6.setStyleSheet("font: 75 italic 24pt \"Palatino Linotype\";\n"
"background:transparent;\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        FRIDAY_AI_ASSISTANT.setCentralWidget(self.centralwidget)

        self.retranslateUi(FRIDAY_AI_ASSISTANT)
        QtCore.QMetaObject.connectSlotsByName(FRIDAY_AI_ASSISTANT)

    def retranslateUi(self, FRIDAY_AI_ASSISTANT):
        _translate = QtCore.QCoreApplication.translate
        FRIDAY_AI_ASSISTANT.setWindowTitle(_translate("FRIDAY_AI_ASSISTANT", "MainWindow"))
        self.pushButton.setText(_translate("FRIDAY_AI_ASSISTANT", "ACTIVATE"))
        self.pushButton_2.setText(_translate("FRIDAY_AI_ASSISTANT", "TERMINATE"))
        self.label_6.setText(_translate("FRIDAY_AI_ASSISTANT", "FRIDAY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FRIDAY_AI_ASSISTANT = QtWidgets.QMainWindow()
    ui = Ui_FRIDAY_AI_ASSISTANT()
    ui.setupUi(FRIDAY_AI_ASSISTANT)
    FRIDAY_AI_ASSISTANT.show()
    sys.exit(app.exec_())
