# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fridayUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fridayUI(object):
    def setupUi(self, fridayUI):
        fridayUI.setObjectName("fridayUI")
        fridayUI.resize(1253, 836)
        self.centralwidget = QtWidgets.QWidget(fridayUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1251, 841))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../Downloads/MImN.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(812, 720, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(980, 720, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 401, 201))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../../Downloads/Jarvis_Loading_Screen.gif"))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(770, 230, 421, 111))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setMouseTracking(False)
        self.textBrowser.setStyleSheet("background: transparent;\n"
"border-radius: none;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(40, 240, 441, 111))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setMouseTracking(False)
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 600, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 490, 421, 181))
        self.label_4.setStyleSheet("font: 75 72pt \"MS Shell Dlg 2\";\n"
"color:#55aaff;\n"
"")
        self.label_4.setObjectName("label_4")
        fridayUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(fridayUI)
        QtCore.QMetaObject.connectSlotsByName(fridayUI)

    def retranslateUi(self, fridayUI):
        _translate = QtCore.QCoreApplication.translate
        fridayUI.setWindowTitle(_translate("fridayUI", "MainWindow"))
        self.pushButton.setText(_translate("fridayUI", "Run"))
        self.pushButton_2.setText(_translate("fridayUI", "Terminate"))
        self.label_3.setText(_translate("fridayUI", "TextLabel"))
        self.label_4.setText(_translate("fridayUI", "FRIDAY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fridayUI = QtWidgets.QMainWindow()
    ui = Ui_fridayUI()
    ui.setupUi(fridayUI)
    fridayUI.show()
    sys.exit(app.exec_())
